# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 8070, host: 8080
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "../data", "/vagrant_data"

    config.vm.define :master do |master|
        master.vm.box = "centos/7"
        master.vm.network "forwarded_port", guest: 8070, host: 8080
        master.vm.network "private_network", ip: "192.168.33.10"
        master.vm.synced_folder "./master", "/vagrant_data"
    end

    config.vm.define :dev do |dev|
        dev.vm.box = "centos/7"
        dev.vm.network "forwarded_port", guest: 8090, host: 8080
        dev.vm.network "private_network", ip: "192.168.33.11"
        dev.vm.synced_folder "./dev", "/vagrant_data"
    end

    config.vm.define :staging do |staging|
        staging.vm.box = "centos/7"
        staging.vm.network "forwarded_port", guest: 9070, host: 8080
        staging.vm.network "private_network", ip: "192.168.33.12"
        staging.vm.synced_folder "./staging", "/vagrant_data"
    end
end
