--- 
- name: play with a {{ var_name }} 
  hosts: dns 
  gather_facts: true
  
 
  vars: 
  - var_name: not-mastery 
 
  tasks: 
  - name: set a variable 
    set_fact: 
      task_var_name: "defined variable" 
 
  - name: task with a {{ task_var_name }} 
    debug: 
      msg: "I am mastery task" 
 
- name: second play with a {{ task_var_name }} 
  hosts: dns 
  gather_facts: true 
 
  tasks: 
  - name: task with a {{ runtime_var_name }} 
    debug: 
      msg: "I am another mastery task"
